import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import { Providers } from '../providers';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Template Mini App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="es" className={geistSans.variable}>
      <body className={geistSans.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
